### ISSUE TITLE
Adding redux-logger

### ISSUE THREAD

**Issue by ozgunbal** [EkinEren/BookStore#3]
[Redux logger](https://github.com/evgenyrodionov/redux-logger) middleware provides better state debugging on console. Instead of subscribing state change and logging manually, this middleware makes  this functionality. 

If NODE_ENV is development, this middleware should be added.Or if it's in production mode  should not be included.

_Note: This issue is only good-to-have. Not must._

**Comment by EkinEren** [comment]
Added redux logger middleware to the project.
